import { ClockDirections } from "../ClockDirections";
import { DOWNRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL, UPRIGHT, UPLEFT, NONE } from "../HORIZONTAL";

const coordsMap: Record<number, ClockDirections[][]> = {
  0: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [VERTICAL, DOWNRIGHT, DOWNLEFT, VERTICAL],
    [VERTICAL, VERTICAL, VERTICAL, VERTICAL],
    [VERTICAL, VERTICAL, VERTICAL, VERTICAL],
    [VERTICAL, UPRIGHT, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  1: [
    [DOWNRIGHT, HORIZONTAL, DOWNLEFT, NONE],
    [UPRIGHT, DOWNLEFT, VERTICAL, NONE],
    [NONE, VERTICAL, VERTICAL, NONE],
    [NONE, VERTICAL, VERTICAL, NONE],
    [DOWNRIGHT, UPLEFT, UPRIGHT, DOWNLEFT],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  2: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [DOWNRIGHT, HORIZONTAL, UPLEFT, VERTICAL],
    [VERTICAL, DOWNRIGHT, HORIZONTAL, UPLEFT],
    [VERTICAL, UPRIGHT, HORIZONTAL, DOWNLEFT],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  3: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [DOWNRIGHT, HORIZONTAL, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [DOWNRIGHT, HORIZONTAL, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  4: [
    [DOWNRIGHT, DOWNLEFT, DOWNRIGHT, DOWNLEFT],
    [VERTICAL, VERTICAL, VERTICAL, VERTICAL],
    [VERTICAL, UPRIGHT, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [NONE, NONE, VERTICAL, VERTICAL],
    [NONE, NONE, UPRIGHT, UPLEFT],
  ],
  5: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [VERTICAL, DOWNRIGHT, HORIZONTAL, UPLEFT],
    [VERTICAL, UPRIGHT, HORIZONTAL, DOWNLEFT],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [DOWNRIGHT, HORIZONTAL, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  6: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [VERTICAL, DOWNRIGHT, HORIZONTAL, UPLEFT],
    [VERTICAL, UPRIGHT, HORIZONTAL, DOWNLEFT],
    [VERTICAL, DOWNRIGHT, DOWNLEFT, VERTICAL],
    [VERTICAL, UPRIGHT, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  7: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [NONE, NONE, VERTICAL, VERTICAL],
    [NONE, NONE, VERTICAL, VERTICAL],
    [NONE, NONE, VERTICAL, VERTICAL],
    [NONE, NONE, UPRIGHT, UPLEFT],
  ],
  8: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [VERTICAL, DOWNRIGHT, DOWNLEFT, VERTICAL],
    [VERTICAL, UPRIGHT, UPLEFT, VERTICAL],
    [VERTICAL, DOWNRIGHT, DOWNLEFT, VERTICAL],
    [VERTICAL, UPRIGHT, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, HORIZONTAL, UPLEFT],
  ],
  9: [
    [DOWNRIGHT, HORIZONTAL, HORIZONTAL, DOWNLEFT],
    [VERTICAL, DOWNRIGHT, DOWNLEFT, VERTICAL],
    [VERTICAL, UPRIGHT, UPLEFT, VERTICAL],
    [UPRIGHT, HORIZONTAL, DOWNLEFT, VERTICAL],
    [NONE, NONE, VERTICAL, VERTICAL],
    [NONE, NONE, UPRIGHT, UPLEFT],
  ],
};

export const getCoordsForDigit = (digit: number): ClockDirections[][] => coordsMap[digit]